const fs = require('fs');
let c = fs.readFileSync('C:/B-Health/frontend/src/components/Header.jsx', 'utf8');

const oldSearch = '        {/* Search - hide on mobile */}\n        <InputGroup size="sm" className="d-none d-md-flex" style={{ width: 200 }}>\n          <InputGroup.Text\n            className="border-end-0"\n            style={{ borderColor: "#ccfbf1", backgroundColor: "#f0fdfa" }}\n          >\n            <Search size={14} color="#0d9488" />\n          </InputGroup.Text>\n          <Form.Control\n            placeholder="Search..."\n            className="border-start-0"\n            style={{ borderColor: "#ccfbf1", backgroundColor: "#f0fdfa", fontSize: 13 }}\n          />\n        </InputGroup>';

const newSearch = '        {/* Global Search */}\n        <div className="position-relative d-none d-md-block" ref={searchRef}>\n          <InputGroup size="sm" style={{ width: 240 }}>\n            <InputGroup.Text className="border-end-0" style={{ borderColor: "#ccfbf1", backgroundColor: "#f0fdfa" }}><Search size={14} color="#0d9488" /></InputGroup.Text>\n            <Form.Control placeholder="Search residents, records..." className="border-start-0" value={searchQuery} onChange={(e) => { setSearchQuery(e.target.value); setShowSearch(true); }} onFocus={() => { if (searchQuery.trim()) setShowSearch(true); }} style={{ borderColor: "#ccfbf1", backgroundColor: "#f0fdfa", fontSize: 13 }} />\n          </InputGroup>\n          {showSearch && searchQuery.trim() && (\n            <div style={{ position: "absolute", right: 0, top: "calc(100% + 8px)", zIndex: 9999, width: 380, backgroundColor: "#fff", borderRadius: 14, boxShadow: "0 8px 32px rgba(0,0,0,0.14)", border: "1px solid #e5e7eb", overflow: "hidden" }}>\n              {searchLoading ? (\n                <div className="text-center py-4" style={{ fontSize: 13, color: "#9ca3af" }}>Searching...</div>\n              ) : searchResults.length === 0 ? (\n                <div className="text-center py-4" style={{ fontSize: 13, color: "#9ca3af" }}>No results found for "{searchQuery}"</div>\n              ) : (\n                <div style={{ maxHeight: 400, overflowY: "auto" }}>\n                  {Object.entries(groupResults).map(([type, items]) => (\n                    <div key={type}>\n                      <div style={{ padding: "6px 14px 4px", backgroundColor: "#f0fdfa", borderBottom: "1px solid #ccfbf1" }}>\n                        <span style={{ fontSize: 10, fontWeight: 700, color: "#0f766e", textTransform: "uppercase", letterSpacing: "0.05em" }}>\n                          {type}{type.endsWith("s") ? "" : "s"} ({items.length})\n                        </span>\n                      </div>\n                      {items.map((r, i) => (\n                        <div\n                          key={r.type + "_" + r.id + "_" + i}\n                          style={{ padding: "10px 14px", borderBottom: "1px solid #f9fafb", cursor: "pointer" }}\n                          onClick={() => handleResultClick(r)}\n                          onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#f0fdfa"}\n                          onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "transparent"}\n                        >\n                          <div style={{ fontSize: 13, fontWeight: 600, color: "#111827" }}>{r.label}</div>\n                          <div style={{ fontSize: 11, color: "#6b7280", marginTop: 1 }}>{r.sub}</div>\n                        </div>\n                      ))}\n                    </div>\n                  ))}\n                </div>\n              )}\n            </div>\n          )}\n        </div>';

c = c.replace(oldSearch, newSearch);
fs.writeFileSync('C:/B-Health/frontend/src/components/Header.jsx', c);
console.log('OK - written', c.length, 'bytes');
